sudo: required
language: php
php:
- '7.1'
services:
- docker
cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - vendor
env:
  global:
    - CACHE_DIR=$HOME/.cache/docker
    - CACHE_APP=$CACHE_DIR/app.tar.gz
    - CACHE_DB=$CACHE_DIR/db.tar.gz
    - APP_ENV=local
    - RUN_LONG=true

before_install:
- phpenv config-rm xdebug.ini
- pip install --user awscli
- cp .env.travis .env
- composer config -g github-oauth.github.com $GITHUB_TOKEN && composer install --no-scripts
- docker-compose build

script:
- docker-compose run --rm -w /app app vendor/bin/phpcs --standard=psr2 app/
- docker-compose run --rm -w /app app vendor/bin/phpunit

deploy:
- provider: script
  script: /bin/sh docker/deploy.bash
  on:
    branch: master

